{"ast":null,"code":"import _initializerDefineProperty from\"/home/chef/Desktop/signer/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/initializerDefineProperty\";import _classCallCheck from\"/home/chef/Desktop/signer/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/classCallCheck\";import _createClass from\"/home/chef/Desktop/signer/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/createClass\";import _applyDecoratedDescriptor from\"/home/chef/Desktop/signer/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/applyDecoratedDescriptor\";import _initializerWarningHelper from\"/home/chef/Desktop/signer/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/initializerWarningHelper\";var _class,_descriptor;import{observable}from'mobx';export var ErrorContainer=(_class=/*#__PURE__*/function(){function ErrorContainer(){_classCallCheck(this,ErrorContainer);_initializerDefineProperty(this,\"lastError\",_descriptor,this);}_createClass(ErrorContainer,[{key:\"capture\",value:// This version just sets the error message.\nfunction capture(p){var _this=this;return p.catch(function(err){_this.lastError=err.message;});}// This version re-raises the error, which, if uncaught, shows up in the console.\n},{key:\"withCapture\",value:function withCapture(p){var _this2=this;return p.catch(function(err){_this2.lastError=err.message;throw err;});}},{key:\"dismissLast\",value:function dismissLast(){this.lastError=null;}}]);return ErrorContainer;}(),(_descriptor=_applyDecoratedDescriptor(_class.prototype,\"lastError\",[observable],{configurable:true,enumerable:true,writable:true,initializer:function initializer(){return null;}})),_class);export default ErrorContainer;","map":{"version":3,"sources":["/home/chef/Desktop/signer/src/popup/container/ErrorContainer.ts"],"names":["observable","ErrorContainer","p","catch","err","lastError","message"],"mappings":"yyBAAA,OAASA,UAAT,KAA2B,MAA3B,CAEA,UAAaC,CAAAA,cAAb,iNAIE;AACA,iBAAQC,CAAR,CAAyC,gBACvC,MAAOA,CAAAA,CAAC,CAACC,KAAF,CAAQ,SAAAC,GAAG,CAAI,CACpB,KAAI,CAACC,SAAL,CAAiBD,GAAG,CAACE,OAArB,CACD,CAFM,CAAP,CAGD,CAED;AAXF,2BAYE,qBAAeJ,CAAf,CAA0C,iBACxC,MAAOA,CAAAA,CAAC,CAACC,KAAF,CAAQ,SAAAC,GAAG,CAAI,CACpB,MAAI,CAACC,SAAL,CAAiBD,GAAG,CAACE,OAArB,CACA,KAAMF,CAAAA,GAAN,CACD,CAHM,CAAP,CAID,CAjBH,2BAmBE,sBAAc,CACZ,KAAKC,SAAL,CAAiB,IAAjB,CACD,CArBH,mGAEGL,UAFH,4FAEyC,KAFzC,cAwBA,cAAeC,CAAAA,cAAf","sourcesContent":["import { observable } from 'mobx';\n\nexport class ErrorContainer {\n  // We can display the last error when it happens.\n  @observable lastError: string | null = null;\n\n  // This version just sets the error message.\n  capture(p: Promise<void>): Promise<void> {\n    return p.catch(err => {\n      this.lastError = err.message;\n    });\n  }\n\n  // This version re-raises the error, which, if uncaught, shows up in the console.\n  withCapture<T>(p: Promise<T>): Promise<T> {\n    return p.catch(err => {\n      this.lastError = err.message;\n      throw err;\n    });\n  }\n\n  dismissLast() {\n    this.lastError = null;\n  }\n}\n\nexport default ErrorContainer;\n"]},"metadata":{},"sourceType":"module"}